//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `sort.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Sorting;

public interface SortFilePrx extends com.zeroc.Ice.ObjectPrx
{
    default boolean createFile()
    {
        return createFile(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean createFile(java.util.Map<String, String> context)
    {
        return _iceI_createFileAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> createFileAsync()
    {
        return _iceI_createFileAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> createFileAsync(java.util.Map<String, String> context)
    {
        return _iceI_createFileAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_createFileAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createFile", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default String[] sortFileList(String[] strings)
    {
        return sortFileList(strings, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] sortFileList(String[] strings, java.util.Map<String, String> context)
    {
        return _iceI_sortFileListAsync(strings, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> sortFileListAsync(String[] strings)
    {
        return _iceI_sortFileListAsync(strings, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> sortFileListAsync(String[] strings, java.util.Map<String, String> context)
    {
        return _iceI_sortFileListAsync(strings, context, false);
    }

    /**
     * @hidden
     * @param iceP_strings -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_sortFileListAsync(String[] iceP_strings, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sortFileList", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeStringSeq(iceP_strings);
                 }, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    default String[][] divideFile(int parts)
    {
        return divideFile(parts, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[][] divideFile(int parts, java.util.Map<String, String> context)
    {
        return _iceI_divideFileAsync(parts, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[][]> divideFileAsync(int parts)
    {
        return _iceI_divideFileAsync(parts, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[][]> divideFileAsync(int parts, java.util.Map<String, String> context)
    {
        return _iceI_divideFileAsync(parts, context, false);
    }

    /**
     * @hidden
     * @param iceP_parts -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[][]> _iceI_divideFileAsync(int iceP_parts, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[][]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "divideFile", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_parts);
                 }, istr -> {
                     String[][] ret;
                     ret = StringSeqSeqHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default String register()
    {
        return register(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String register(java.util.Map<String, String> context)
    {
        return _iceI_registerAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> registerAsync()
    {
        return _iceI_registerAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> registerAsync(java.util.Map<String, String> context)
    {
        return _iceI_registerAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_registerAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "register", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void waitForAllClients()
    {
        waitForAllClients(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void waitForAllClients(java.util.Map<String, String> context)
    {
        _iceI_waitForAllClientsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> waitForAllClientsAsync()
    {
        return _iceI_waitForAllClientsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> waitForAllClientsAsync(java.util.Map<String, String> context)
    {
        return _iceI_waitForAllClientsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_waitForAllClientsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "waitForAllClients", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SortFilePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), SortFilePrx.class, _SortFilePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SortFilePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), SortFilePrx.class, _SortFilePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SortFilePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), SortFilePrx.class, _SortFilePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SortFilePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), SortFilePrx.class, _SortFilePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static SortFilePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, SortFilePrx.class, _SortFilePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static SortFilePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, SortFilePrx.class, _SortFilePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default SortFilePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (SortFilePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default SortFilePrx ice_adapterId(String newAdapterId)
    {
        return (SortFilePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default SortFilePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (SortFilePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default SortFilePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (SortFilePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default SortFilePrx ice_invocationTimeout(int newTimeout)
    {
        return (SortFilePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default SortFilePrx ice_connectionCached(boolean newCache)
    {
        return (SortFilePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default SortFilePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (SortFilePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SortFilePrx ice_secure(boolean b)
    {
        return (SortFilePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default SortFilePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (SortFilePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SortFilePrx ice_preferSecure(boolean b)
    {
        return (SortFilePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default SortFilePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (SortFilePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default SortFilePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (SortFilePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default SortFilePrx ice_collocationOptimized(boolean b)
    {
        return (SortFilePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default SortFilePrx ice_twoway()
    {
        return (SortFilePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default SortFilePrx ice_oneway()
    {
        return (SortFilePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default SortFilePrx ice_batchOneway()
    {
        return (SortFilePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default SortFilePrx ice_datagram()
    {
        return (SortFilePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default SortFilePrx ice_batchDatagram()
    {
        return (SortFilePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default SortFilePrx ice_compress(boolean co)
    {
        return (SortFilePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default SortFilePrx ice_timeout(int t)
    {
        return (SortFilePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default SortFilePrx ice_connectionId(String connectionId)
    {
        return (SortFilePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default SortFilePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (SortFilePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Sorting::SortFile";
    }
}
